UPDATE trips SET latitude = -8.4095,  longitude = 115.1889 WHERE LOWER(destination) LIKE '%bali%'       AND latitude IS NULL;
UPDATE trips SET latitude = -1.2921,  longitude = 36.8219  WHERE LOWER(destination) LIKE '%kenia%'      AND latitude IS NULL;
UPDATE trips SET latitude = -1.2921,  longitude = 36.8219  WHERE LOWER(destination) LIKE '%nairobi%'    AND latitude IS NULL;
UPDATE trips SET latitude = 35.6762,  longitude = 139.6503 WHERE LOWER(destination) LIKE '%tokio%'      AND latitude IS NULL;
UPDATE trips SET latitude = 35.6762,  longitude = 139.6503 WHERE LOWER(destination) LIKE '%jap%'        AND latitude IS NULL;
UPDATE trips SET latitude = 43.7696,  longitude = 11.2558  WHERE LOWER(destination) LIKE '%florencia%'  AND latitude IS NULL;
UPDATE trips SET latitude = 3.2028,   longitude = 73.2207  WHERE LOWER(destination) LIKE '%maldivas%'   AND latitude IS NULL;
UPDATE trips SET latitude = 40.7128,  longitude = -74.0060 WHERE LOWER(destination) LIKE '%nueva york%' AND latitude IS NULL;
UPDATE trips SET latitude = 47.3769,  longitude = 8.5417   WHERE LOWER(destination) LIKE '%suiza%'      AND latitude IS NULL;
UPDATE trips SET latitude = 41.3851,  longitude = 2.1734   WHERE LOWER(destination) LIKE '%barcelona%'  AND latitude IS NULL;
UPDATE trips SET latitude = 31.6295,  longitude = -7.9811  WHERE LOWER(destination) LIKE '%marrakech%'  AND latitude IS NULL;
UPDATE trips SET latitude = 31.7917,  longitude = -7.0926  WHERE LOWER(destination) LIKE '%marruecos%'  AND latitude IS NULL;
UPDATE trips SET latitude = 9.7489,   longitude = -83.7534 WHERE LOWER(destination) LIKE '%costa rica%' AND latitude IS NULL;
UPDATE trips SET latitude = 64.1466,  longitude = -21.9426 WHERE LOWER(destination) LIKE '%islandia%'   AND latitude IS NULL;
UPDATE trips SET latitude = 64.1466,  longitude = -21.9426 WHERE LOWER(destination) LIKE '%reikiavik%'  AND latitude IS NULL;
UPDATE trips SET latitude = 21.1619,  longitude = -86.8515 WHERE LOWER(destination) LIKE '%canc%'       AND latitude IS NULL;
UPDATE trips SET latitude = 21.1619,  longitude = -86.8515 WHERE LOWER(destination) LIKE '%mexico%'     AND latitude IS NULL;
UPDATE trips SET latitude = 21.1619,  longitude = -86.8515 WHERE LOWER(destination) LIKE '%m%xico%'     AND latitude IS NULL;
UPDATE trips SET latitude = 41.9028,  longitude = 12.4964  WHERE LOWER(destination) LIKE '%roma%'       AND latitude IS NULL;
UPDATE trips SET latitude = 48.8566,  longitude = 2.3522   WHERE LOWER(destination) LIKE '%paris%'      AND latitude IS NULL;
UPDATE trips SET latitude = 48.8566,  longitude = 2.3522   WHERE LOWER(destination) LIKE '%par%s%'      AND latitude IS NULL;
UPDATE trips SET latitude = 51.5074,  longitude = -0.1278  WHERE LOWER(destination) LIKE '%londre%'     AND latitude IS NULL;
UPDATE trips SET latitude = 37.3891,  longitude = -5.9845  WHERE LOWER(destination) LIKE '%sevilla%'    AND latitude IS NULL;
UPDATE trips SET latitude = 42.2883,  longitude = 3.2794   WHERE LOWER(destination) LIKE '%cadaqu%'     AND latitude IS NULL;
UPDATE trips SET latitude = 38.7223,  longitude = -9.1393  WHERE LOWER(destination) LIKE '%lisboa%'     AND latitude IS NULL;
UPDATE trips SET latitude = 42.6019,  longitude = 0.5219   WHERE LOWER(destination) LIKE '%benasque%'   AND latitude IS NULL;
UPDATE trips SET latitude = 37.1773,  longitude = -3.5986  WHERE LOWER(destination) LIKE '%granada%'    AND latitude IS NULL;
UPDATE trips SET latitude = 41.0667,  longitude = -2.6333  WHERE LOWER(destination) LIKE '%sig%'        AND latitude IS NULL;
UPDATE trips SET latitude = 28.2916,  longitude = -16.6291 WHERE LOWER(destination) LIKE '%tenerife%'   AND latitude IS NULL;
UPDATE trips SET latitude = 39.5696,  longitude = 2.6502   WHERE LOWER(destination) LIKE '%mallorca%'   AND latitude IS NULL;
UPDATE trips SET latitude = 40.4168,  longitude = -3.7038  WHERE LOWER(destination) LIKE '%madrid%'     AND latitude IS NULL;
UPDATE trips SET latitude = 37.9922,  longitude = -1.1307  WHERE LOWER(destination) LIKE '%murcia%'     AND latitude IS NULL;
UPDATE trips SET latitude = 43.2630,  longitude = -2.9350  WHERE LOWER(destination) LIKE '%bilbao%'     AND latitude IS NULL;
UPDATE trips SET latitude = 43.3619,  longitude = -5.8494  WHERE LOWER(destination) LIKE '%asturias%'   AND latitude IS NULL;
UPDATE trips SET latitude = 42.8782,  longitude = -8.5448  WHERE LOWER(destination) LIKE '%santiago%'   AND latitude IS NULL;
UPDATE trips SET latitude = 51.2194,  longitude = 4.4025   WHERE LOWER(destination) LIKE '%amberes%'    AND latitude IS NULL;
UPDATE trips SET latitude = 50.8503,  longitude = 4.3517   WHERE LOWER(destination) LIKE '%bruselas%'   AND latitude IS NULL;
UPDATE trips SET latitude = 52.3676,  longitude = 4.9041   WHERE LOWER(destination) LIKE '%amsterdam%'  AND latitude IS NULL;
UPDATE trips SET latitude = 55.6761,  longitude = 12.5683  WHERE LOWER(destination) LIKE '%copenhague%' AND latitude IS NULL;
UPDATE trips SET latitude = 59.9139,  longitude = 10.7522  WHERE LOWER(destination) LIKE '%oslo%'       AND latitude IS NULL;
UPDATE trips SET latitude = 59.3293,  longitude = 18.0686  WHERE LOWER(destination) LIKE '%estocolmo%'  AND latitude IS NULL;
UPDATE trips SET latitude = 60.1699,  longitude = 24.9384  WHERE LOWER(destination) LIKE '%helsinki%'   AND latitude IS NULL;
UPDATE trips SET latitude = 37.9838,  longitude = 23.7275  WHERE LOWER(destination) LIKE '%atenas%'     AND latitude IS NULL;
UPDATE trips SET latitude = 41.0082,  longitude = 28.9784  WHERE LOWER(destination) LIKE '%estambul%'   AND latitude IS NULL;
UPDATE trips SET latitude = 25.2048,  longitude = 55.2708  WHERE LOWER(destination) LIKE '%dubai%'      AND latitude IS NULL;
UPDATE trips SET latitude = 1.3521,   longitude = 103.8198 WHERE LOWER(destination) LIKE '%singapur%'   AND latitude IS NULL;
UPDATE trips SET latitude = 22.3193,  longitude = 114.1694 WHERE LOWER(destination) LIKE '%hong kong%'  AND latitude IS NULL;
UPDATE trips SET latitude = 13.7563,  longitude = 100.5018 WHERE LOWER(destination) LIKE '%bangkok%'    AND latitude IS NULL;
UPDATE trips SET latitude = -33.8688, longitude = 151.2093 WHERE LOWER(destination) LIKE '%s%dney%'     AND latitude IS NULL;
UPDATE trips SET latitude = -37.8136, longitude = 144.9631 WHERE LOWER(destination) LIKE '%melbourne%'  AND latitude IS NULL;
UPDATE trips SET latitude = -22.9068, longitude = -43.1729 WHERE LOWER(destination) LIKE '%r%o de janeiro%' AND latitude IS NULL;
UPDATE trips SET latitude = -23.5505, longitude = -46.6333 WHERE LOWER(destination) LIKE '%s%o paulo%'  AND latitude IS NULL;
UPDATE trips SET latitude = -34.6037, longitude = -58.3816 WHERE LOWER(destination) LIKE '%buenos aires%' AND latitude IS NULL;
UPDATE trips SET latitude = -13.5320, longitude = -71.9675 WHERE LOWER(destination) LIKE '%cusco%'      AND latitude IS NULL;
UPDATE trips SET latitude = -12.0464, longitude = -77.0428 WHERE LOWER(destination) LIKE '%lima%'       AND latitude IS NULL;
UPDATE trips SET latitude = 19.4326,  longitude = -99.1332 WHERE LOWER(destination) LIKE '%ciudad de m%xico%' AND latitude IS NULL;
UPDATE trips SET latitude = 4.7110,   longitude = -74.0721 WHERE LOWER(destination) LIKE '%bogot%'      AND latitude IS NULL;
UPDATE trips SET latitude = 30.0444,  longitude = 31.2357  WHERE LOWER(destination) LIKE '%el cairo%'   AND latitude IS NULL;
UPDATE trips SET latitude = -4.0435,  longitude = 39.6682  WHERE LOWER(destination) LIKE '%mombasa%'    AND latitude IS NULL;
UPDATE trips SET latitude = -26.2041, longitude = 28.0473  WHERE LOWER(destination) LIKE '%johannesburgo%' AND latitude IS NULL;
UPDATE trips SET latitude = 33.8869,  longitude = 9.5375   WHERE LOWER(destination) LIKE '%t%nez%'      AND latitude IS NULL;
UPDATE trips SET latitude = 36.8065,  longitude = 10.1815  WHERE LOWER(destination) LIKE '%t%nez%'      AND latitude IS NULL;
UPDATE trips SET latitude = 28.0339,  longitude = 1.6596   WHERE LOWER(destination) LIKE '%argelia%'    AND latitude IS NULL;